import type { HustlerSpot } from '../core/types';
import type { World } from './arenaWorld';

/**
 * WHERE THE STREET HUSTLERS WORK (`src/sim/hustlers.ts`), as a LAYER over the open world — the same
 * one-way dependency as the race doors (`cityStreetSites.ts`): the city does not know they exist.
 *
 * TRAPITOS, each pointing at a space at the kerb nobody is going to park in, and each beside a
 * traffic light of his own (the washers' kind, but only scenery: nothing stops for it). Nine stand
 * at places a player already goes —
 *     - outside Loco Mustang's garage, on the boulevard end of its frontage,
 *     - at the car meet's main gate off blvd-ring-s, under the viaduct's curve (La Curva's door),
 *     - on the NEOGAS forecourt's pavement where the two ring boulevards cross,
 *     - beside the EV chargers on av-s2 in the south-west neon district,
 *     - on the wide pavement beside the Bandido Grid start line on av-s1,
 *     - down the ring boulevard from the Rayo Rush door, on blvd-ring-s's south kerb,
 *     - on av-s1's south kerb at the market, across from its bus stop,
 *     - on the MAREA forecourt's pavement along the quay's waterfront boulevard,
 *     - on blvd-ring-n's north kerb just east of blvd-ring-e, the far north-east corner of the ring.
 *   — and eighteen more work street corners spread over the whole grid, at least ~120 m from any
 *   other hustler: each stands a few steps back from the corner on the kerb of the one approach
 *   whose near-right corner it is (right-hand traffic), with his light on the corner facing it.
 *
 *   WASHERS, each working the one approach whose kerb corner he stands on, at his own light —
 *     - av-s1 eastbound at st-w3, under the viaduct's west ramp, a block from the VOLTA station
 *       and the meet,
 *     - av-central northbound at blvd-ring-s: the way into downtown, straight up from the spawn,
 *     - av-e1 southbound at st-south, on the OCTANO station's corner in the industrial east.
 *
 *   SOCK SELLERS, each walking 36 m of a straight pavement mid-block and back, clear of every
 *   corner, bus stop, micro-scene and other hustler —
 *     - av-central's east pavement, a hundred metres up from the spawn on the way into downtown,
 *     - st-oldtown's west pavement, south of the ring,
 *     - st-w3's east pavement, a block south of Loco Mustang's garage and the meet,
 *     - blvd-ring-w's east pavement, on the ring's west side,
 *     - st-e3's east pavement, out in the industrial east.
 *   A seller's `x`/`z` is the middle of his walk.
 *
 *   TRAVESTIS, each on the edge of a road at night, facing it —
 *     - seven round the Bosques' loop (`metroPark.ts`): under the west woods, up in the north-west
 *       trees, along the north leg, the north-east bend, the east leg past the planetarium, and
 *       on the city-side pavement of the south leg at either end — all clear of the park's
 *       meeting places,
 *     - under the viaduct's east leg, beside the columns,
 *     - on the kerb at the villa's edge, off blvd-ring-e,
 *     - on the waterfront boulevard at the docks.
 *
 * Every spot stands on pavement, every washer's car waits on his approach's lane, every seller's
 * whole walk is pavement, and none of them is inside anything solid (`tests/hustlers.test.ts`). The coordinates were read off the built
 * world, not the spec: kerb lines, lot edges and the ramp are where the assembler put them.
 *
 * Headings follow the game's convention: 0 faces north (-z), π/2 faces east.
 */

const N = 0;
const E = Math.PI / 2;
const S = Math.PI;
const W = -Math.PI / 2;

/** Seeds were chosen so the first twelve dress differently: hoods, bucket hats, caps, messy hair, shorts, every shirt. */
export const METRO_HUSTLER_SPOTS: HustlerSpot[] = [
  {
    id: 'trapito-garage',
    kind: 'trapito',
    label: "LOCO MUSTANG'S GARAGE",
    x: -446.5,
    z: 232.6,
    heading: N,
    seed: 1,
    space: { x: -452.5, z: 227.8 },
    signal: { x: -449.5, z: 230.8, heading: W, offset: 11 },
  },
  {
    id: 'trapito-meet-gate',
    kind: 'trapito',
    label: 'LA CURVA · MEET GATE',
    x: -563.2,
    z: 231.8,
    heading: N,
    seed: 13,
    space: { x: -575, z: 239 },
    signal: { x: -566.2, z: 230.8, heading: W, offset: 26 },
  },
  {
    id: 'trapito-neogas',
    kind: 'trapito',
    label: 'NEOGAS · RING NORTH',
    x: -398,
    z: -472.6,
    heading: S,
    seed: 42,
    space: { x: -391.5, z: -467.8 },
    signal: { x: -395, z: -470.8, heading: E, offset: 33 },
  },
  {
    id: 'trapito-chargers',
    kind: 'trapito',
    label: 'AV SOUTH 2 · THE CHARGERS',
    x: -403.2,
    z: 768.6,
    heading: S,
    seed: 178,
    space: { x: -410.5, z: 773.2 },
    signal: { x: -400.2, z: 770.2, heading: E, offset: 8 },
  },
  {
    id: 'trapito-grid',
    kind: 'trapito',
    label: 'BANDIDO GRID',
    x: -126,
    z: 487.5,
    heading: S,
    seed: 92,
    space: { x: -132.5, z: 494.2 },
    signal: { x: -123, z: 490.2, heading: E, offset: 37 },
  },
  {
    id: 'trapito-rush',
    kind: 'trapito',
    label: 'RAYO RUSH · RING SOUTH',
    x: -195,
    z: 232.5,
    heading: N,
    seed: 15,
    space: { x: -201.5, z: 227.8 },
    signal: { x: -198, z: 230.8, heading: W, offset: 9 },
  },
  {
    id: 'trapito-market',
    kind: 'trapito',
    label: 'AV SOUTH · THE MARKET',
    x: 228,
    z: 510.6,
    heading: N,
    seed: 35,
    space: { x: 221.5, z: 506.2 },
    signal: { x: 225, z: 509.8, heading: W, offset: 34 },
  },
  {
    id: 'trapito-marea',
    kind: 'trapito',
    label: 'MAREA · THE QUAY',
    x: 185,
    z: 1176.7,
    heading: S,
    seed: 71,
    space: { x: 191.5, z: 1180.8 },
    signal: { x: 188, z: 1177.2, heading: E, offset: 1 },
  },
  {
    id: 'trapito-ring-ne',
    kind: 'trapito',
    label: 'RING NORTH × RING EAST',
    x: 380,
    z: -472.6,
    heading: S,
    seed: 67,
    space: { x: 386.5, z: -467.8 },
    signal: { x: 383, z: -470.8, heading: E, offset: 35 },
  },
  {
    id: 'washer-volta',
    kind: 'washer',
    label: 'AV SOUTH × ST WEST 3',
    x: -488.6,
    z: 511.1,
    heading: N,
    seed: 2,
    approach: { x: -491.5, z: 504.6, heading: E },
    signal: { x: -487.2, z: 510, heading: W, offset: 0 },
  },
  {
    id: 'washer-downtown',
    kind: 'washer',
    label: 'AV CENTRAL × RING SOUTH',
    x: -47,
    z: 232.4,
    heading: W,
    seed: 50,
    approach: { x: -54.5, z: 235, heading: N },
    signal: { x: -48.4, z: 231, heading: S, offset: 13 },
  },
  {
    id: 'washer-octano',
    kind: 'washer',
    label: 'AV EAST × ST SOUTH',
    x: 609.2,
    z: 1.9,
    heading: E,
    seed: 5,
    approach: { x: 614.5, z: -1, heading: S },
    signal: { x: 610.2, z: 3, heading: N, offset: 26 },
  },
  {
    id: 'trapito-centre-n3',
    kind: 'trapito',
    label: 'ST CENTRE × ST N3',
    x: 38.7,
    z: -587,
    heading: W,
    seed: 104,
    space: { x: 34.2, z: -581.5 },
    signal: { x: 37.3, z: -592.7, heading: S, offset: 26 },
  },
  {
    id: 'trapito-ring-w-water',
    kind: 'trapito',
    label: 'RING W × THE QUAY',
    x: -352.2,
    z: 1171.5,
    heading: E,
    seed: 23,
    space: { x: -347.7, z: 1166 },
    signal: { x: -350.8, z: 1177.2, heading: N, offset: 5 },
  },
  {
    id: 'trapito-w3-gran-via',
    kind: 'trapito',
    label: 'ST W3 × GRAN VÍA',
    x: -493,
    z: -167.8,
    heading: N,
    seed: 88,
    space: { x: -498.5, z: -172.3 },
    signal: { x: -487.3, z: -169.2, heading: W, offset: 31 },
  },
  {
    id: 'trapito-w1-s5',
    kind: 'trapito',
    label: 'AV W1 × ST S5',
    x: -631.2,
    z: 907,
    heading: E,
    seed: 131,
    space: { x: -626.7, z: 901.5 },
    signal: { x: -629.8, z: 912.7, heading: N, offset: 20 },
  },
  {
    id: 'trapito-oldtown-s5',
    kind: 'trapito',
    label: 'ST OLDTOWN × ST S5',
    x: 147.5,
    z: 928.7,
    heading: N,
    seed: 57,
    space: { x: 142, z: 924.2 },
    signal: { x: 153.2, z: 927.3, heading: W, offset: 9 },
  },
  {
    id: 'trapito-centre-s4',
    kind: 'trapito',
    label: 'ST CENTRE × ST S4',
    x: 43,
    z: 631.3,
    heading: S,
    seed: 9,
    space: { x: 48.5, z: 635.8 },
    signal: { x: 37.3, z: 632.7, heading: E, offset: 24 },
  },
  {
    id: 'trapito-ring-e-gran-via',
    kind: 'trapito',
    label: 'RING E × GRAN VÍA',
    x: 356.5,
    z: -192.2,
    heading: S,
    seed: 146,
    space: { x: 362, z: -187.7 },
    signal: { x: 350.8, z: -190.8, heading: E, offset: 8 },
  },
  {
    id: 'trapito-ring-e-s6',
    kind: 'trapito',
    label: 'RING E × ST S6',
    x: 327.8,
    z: 1047,
    heading: E,
    seed: 61,
    space: { x: 332.3, z: 1041.5 },
    signal: { x: 329.2, z: 1052.7, heading: N, offset: 37 },
  },
  {
    id: 'trapito-e3-s3',
    kind: 'trapito',
    label: 'OBELISCO · 9 DE JULIO',
    x: 439.8,
    z: 347,
    heading: E,
    seed: 112,
    space: { x: 444.3, z: 341.5 },
    signal: { x: 441.2, z: 352.7, heading: N, offset: 4 },
  },
  {
    id: 'trapito-w1-n3',
    kind: 'trapito',
    label: 'AV W1 × ST N3',
    x: -635.5,
    z: -591.3,
    heading: N,
    seed: 29,
    space: { x: -641, z: -595.8 },
    signal: { x: -629.8, z: -592.7, heading: W, offset: 8 },
  },
  {
    id: 'trapito-west-south',
    kind: 'trapito',
    label: 'ST WEST × ST SOUTH',
    x: -265,
    z: 18.7,
    heading: N,
    seed: 77,
    space: { x: -270.5, z: 14.2 },
    signal: { x: -259.3, z: 17.3, heading: W, offset: 32 },
  },
  {
    id: 'trapito-e3-s2',
    kind: 'trapito',
    label: 'ST E3 × AV S2',
    x: 467,
    z: 791.2,
    heading: N,
    seed: 160,
    space: { x: 461.5, z: 786.7 },
    signal: { x: 472.7, z: 789.8, heading: W, offset: 28 },
  },
  {
    id: 'trapito-centre-mid',
    kind: 'trapito',
    label: 'ST CENTRE × ST MID',
    x: 21.3,
    z: -93,
    heading: E,
    seed: 44,
    space: { x: 25.8, z: -98.5 },
    signal: { x: 22.7, z: -87.3, heading: N, offset: 35 },
  },
  {
    id: 'trapito-e1-water',
    kind: 'trapito',
    label: 'AV E1 × THE QUAY',
    x: 635.5,
    z: 1175.8,
    heading: S,
    seed: 95,
    space: { x: 641, z: 1180.3 },
    signal: { x: 629.8, z: 1177.2, heading: E, offset: 2 },
  },
  {
    id: 'trapito-east-ring-s',
    kind: 'trapito',
    label: 'ST EAST × RING S',
    x: 258.7,
    z: 236.5,
    heading: W,
    seed: 123,
    space: { x: 254.2, z: 242 },
    signal: { x: 257.3, z: 230.8, heading: S, offset: 3 },
  },
  {
    id: 'trapito-west-gran-via',
    kind: 'trapito',
    label: 'ST WEST × GRAN VÍA',
    x: -260.7,
    z: -196.5,
    heading: E,
    seed: 18,
    space: { x: -256.2, z: -202 },
    signal: { x: -259.3, z: -190.8, heading: N, offset: 9 },
  },
  {
    id: 'trapito-e1-s4',
    kind: 'trapito',
    label: 'AV E1 × ST S4',
    x: 608.8,
    z: 627,
    heading: E,
    seed: 139,
    space: { x: 613.3, z: 621.5 },
    signal: { x: 610.2, z: 632.7, heading: N, offset: 37 },
  },
  {
    id: 'trapito-oldtown-south',
    kind: 'trapito',
    label: 'ST OLDTOWN × ST SOUTH',
    x: 168.2,
    z: 23,
    heading: W,
    seed: 83,
    space: { x: 163.7, z: 28.5 },
    signal: { x: 166.8, z: 17.3, heading: S, offset: 35 },
  },
  {
    id: 'medias-av-central',
    kind: 'medias',
    label: 'AV CENTRAL · SOCKS',
    x: -46.3,
    z: 327.5,
    heading: W,
    seed: 101,
    beat: { from: { x: -46.3, z: 309.5 }, to: { x: -46.3, z: 345.5 } },
  },
  {
    id: 'medias-oldtown',
    kind: 'medias',
    label: 'ST OLDTOWN · SOCKS',
    x: 151.3,
    z: 249.5,
    heading: E,
    seed: 102,
    beat: { from: { x: 151.3, z: 231.5 }, to: { x: 151.3, z: 267.5 } },
  },
  {
    id: 'medias-garage',
    kind: 'medias',
    label: 'ST WEST 3 · SOCKS',
    x: -470.8,
    z: 320.5,
    heading: W,
    seed: 103,
    beat: { from: { x: -470.8, z: 302.5 }, to: { x: -470.8, z: 338.5 } },
  },
  {
    id: 'medias-ring-w',
    kind: 'medias',
    label: 'RING WEST · SOCKS',
    x: -327.3,
    z: 56.5,
    heading: W,
    seed: 104,
    beat: { from: { x: -327.3, z: 38.5 }, to: { x: -327.3, z: 74.5 } },
  },
  {
    id: 'medias-east',
    kind: 'medias',
    label: 'ST EAST 3 · SOCKS',
    x: 489.3,
    z: 38.5,
    heading: W,
    seed: 105,
    beat: { from: { x: 489.3, z: 20.5 }, to: { x: 489.3, z: 56.5 } },
  },
  {
    id: 'travesti-bosque-oeste',
    kind: 'travesti',
    label: 'BOSQUES · LOOP WEST',
    x: -629.4,
    z: -863.2,
    heading: 1.802,
    seed: 201,
  },
  {
    id: 'travesti-bosque-noroeste',
    kind: 'travesti',
    label: 'BOSQUES · NORTH-WEST WOODS',
    x: -446.3,
    z: -1065.3,
    heading: 2.678,
    seed: 202,
  },
  {
    id: 'travesti-loop-norte',
    kind: 'travesti',
    label: 'BOSQUES · NORTH LEG',
    x: -13.4,
    z: -1074.9,
    heading: -0.235,
    seed: 203,
  },
  {
    id: 'travesti-loop-noreste',
    kind: 'travesti',
    label: 'BOSQUES · NORTH-EAST BEND',
    x: 492.9,
    z: -1038.5,
    heading: 0.329,
    seed: 204,
  },
  {
    id: 'travesti-loop-este',
    kind: 'travesti',
    label: 'BOSQUES · EAST LEG',
    x: 613.8,
    z: -794.5,
    heading: -1.095,
    seed: 205,
  },
  {
    id: 'travesti-loop-sur-este',
    kind: 'travesti',
    label: 'BOSQUES · SOUTH LEG EAST',
    x: 366.8,
    z: -712.5,
    heading: 0.131,
    seed: 206,
  },
  {
    id: 'travesti-loop-sur-oeste',
    kind: 'travesti',
    label: 'BOSQUES · SOUTH LEG WEST',
    x: -414.1,
    z: -688.7,
    heading: -0.043,
    seed: 207,
  },
  {
    id: 'travesti-bajo-autopista',
    kind: 'travesti',
    label: 'UNDER THE VIADUCT · EAST',
    x: 520,
    z: 410,
    heading: W,
    seed: 208,
  },
  {
    id: 'travesti-villa',
    kind: 'travesti',
    label: 'LA VILLA · RING EAST',
    x: 362,
    z: 648,
    heading: N,
    seed: 209,
  },
  {
    id: 'travesti-puerto',
    kind: 'travesti',
    label: 'THE QUAY · DOCKS',
    x: -178,
    z: 1196,
    heading: N,
    seed: 210,
  },
];

/** Put the hustlers on a world's layout. Before the street props, which keep clear of them. */
export function addHustlers(world: World, spots: readonly HustlerSpot[] = METRO_HUSTLER_SPOTS): World {
  // Each stands on the ground where the city puts its ground: the spots are written flat.
  const groundY = world.layout.groundY;
  world.layout.hustlerSpots = spots.map((s) => ({ ...s, y: groundY ? groundY(s.x, s.z) : 0 }));
  return world;
}
