/**
 * Shared simulation contracts for Rayo Bandido.
 *
 * RULES
 * - This file is the contract between input, simulation, rendering and UI.
 * - Nothing in here may import Three.js or touch the DOM. Simulation state is plain data
 *   so it can later be serialized for multiplayer.
 * - Coordinate system (matches Three.js world space, Y up):
 *     * The world is planar. Positions are (x, z); y = 0 is the road surface.
 *     * `heading` is a compass-style yaw in radians, CLOCKWISE when viewed from above.
 *       heading 0 points toward -Z (the Three.js "forward" convention).
 *     * forward = (sin(heading), -cos(heading)),  right = (cos(heading), sin(heading)).
 *       Use helpers in `src/core/math.ts` instead of re-deriving these.
 *     * Positive steer / positive yaw turns the car to the RIGHT and INCREASES heading.
 *     * Presentation maps a heading to Three.js with `object.rotation.y = -heading`
 *       and models the car nose pointing toward local -Z. Only `src/render/sync.ts`
 *       performs that mapping.
 * - Units: meters, seconds, radians, m/s. Speed HUD conversion to km/h happens in UI.
 */

/** One tick of player intent. Produced by the input layer; consumed by the simulation. */
export interface PlayerCommand {
  /** 0..1 forward throttle. */
  throttle: number;
  /** 0..1 brake. When the car is (nearly) stopped, brake becomes reverse throttle. */
  brake: number;
  /** -1..1 steering; negative = left, positive = right. */
  steer: number;
  /** Handbrake held. */
  handbrake: boolean;
  /** Nitro held. */
  nitro: boolean;
  /** Fire lightning. Edge-triggered: true for exactly one simulation tick per key press. */
  fire: boolean;
  /** Restart. Edge-triggered: true for exactly one simulation tick per key press. */
  restart: boolean;
}

export interface VehicleState {
  x: number;
  z: number;
  heading: number;
  /** Pose at the start of the current tick, for render interpolation. */
  prevX: number;
  prevZ: number;
  prevHeading: number;
  /** World-space velocity in m/s. */
  vx: number;
  vz: number;
  /** Yaw rate in rad/s (positive = turning right). */
  yawRate: number;
  /** Signed longitudinal speed in m/s along the car's forward axis (negative when reversing). */
  speed: number;
  /** Lateral speed in m/s along the car's right axis. */
  lateralSpeed: number;
  /** Signed slip angle in radians between heading and velocity direction (0 when not moving). */
  slipAngle: number;
  /** Current front wheel steering angle in radians (visual + physics). */
  steerAngle: number;
  /** Accumulated wheel rotation in radians for visuals. Wrapped to avoid unbounded growth. */
  wheelSpin: number;
  /** Throttle actually applied this tick (0..1), after nitro modifiers. */
  throttleApplied: number;
  /** Brake actually applied this tick (0..1). */
  brakeApplied: number;
  handbrake: boolean;
  /** True on the tick a collision impulse was applied. Presentation uses it for feedback. */
  collided: boolean;
  /** Speed lost in the last collision (m/s), 0 when no collision this tick. */
  collisionImpact: number;
}

export interface DriftState {
  /** True while a valid drift is being sustained. */
  active: boolean;
  /** Seconds the current drift has lasted (0 when inactive). */
  duration: number;
  /** Seconds slip conditions have been met while not yet active (activation hysteresis). */
  candidateTime: number;
  /** Seconds slip conditions have failed while active (cancellation grace). */
  lapseTime: number;
  /** Number of drifts chained without the chain window expiring. */
  chain: number;
  /** Seconds remaining in which a new drift extends the chain. */
  chainWindow: number;
  /** Charge generated by the drift on the last tick (units per second), for feedback. */
  chargeRate: number;
}

export interface NitroState {
  /** 0..capacity. */
  amount: number;
  /** True while boost is applied this tick. */
  active: boolean;
  /** Seconds until recharge resumes after boosting (short delay so recharge is readable). */
  rechargeDelay: number;
}

export interface LightningState {
  /** 0..capacity. Only drifting adds charge. */
  charge: number;
  /** Id of the target currently inside the auto-aim cone and nearest, or -1. */
  acquiredTargetId: number;
  /** Seconds until the next shot may be fired. */
  cooldown: number;
  /** Seconds remaining on the last arc for presentation (informational). */
  arcTimer: number;
  /** Last fired target id (or -1). */
  lastTargetId: number;
}

export type TargetStatus = 'active' | 'disabled' | 'destroyed';

export interface TargetState {
  id: number;
  x: number;
  z: number;
  heading: number;
  prevX: number;
  prevZ: number;
  prevHeading: number;
  /** World-space knockback velocity (m/s) from being bumped by the player. Decays to 0. */
  vx: number;
  vz: number;
  status: TargetStatus;
  /** Sim time when the target was hit, or -1. */
  hitTime: number;
  /** Simple patrol progress. Implementation detail of `src/sim/targets.ts`. */
  patrolIndex: number;
  patrolSpeed: number;
  /** Whether a reward has already been paid for this target. Guards against duplicate money. */
  rewarded: boolean;
}

export interface EconomyState {
  money: number;
  destroyed: number;
  /** Money gained on the last tick (0 when nothing happened). For HUD flashes. */
  lastReward: number;
}

/** Discrete happenings for presentation and audio. Cleared at the start of every tick. */
export type GameEvent =
  | { type: 'driftStart' }
  | { type: 'driftEnd'; duration: number; chain: number }
  | { type: 'nitroStart' }
  | { type: 'nitroEnd' }
  | { type: 'lightningFired'; targetId: number; fromX: number; fromZ: number; toX: number; toZ: number }
  | { type: 'lightningDenied'; reason: 'noCharge' | 'noTarget' | 'cooldown' }
  | { type: 'targetDestroyed'; targetId: number; x: number; z: number; reward: number }
  | { type: 'collision'; x: number; z: number; impact: number }
  | { type: 'restart' };

export interface GameState {
  /** Simulation time in seconds since the session started. */
  time: number;
  tick: number;
  vehicle: VehicleState;
  drift: DriftState;
  nitro: NitroState;
  lightning: LightningState;
  targets: TargetState[];
  economy: EconomyState;
  events: GameEvent[];
}

/** Axis-aligned obstacle in world space. Buildings, barriers and arena walls. */
export interface ObstacleBox {
  minX: number;
  maxX: number;
  minZ: number;
  maxZ: number;
  /** Optional tag for debugging / presentation. */
  tag?: string;
}

export interface SpawnPoint {
  x: number;
  z: number;
  heading: number;
}

/** Static arena data consumed by both the simulation (collision, spawns) and the renderer. */
export interface ArenaLayout {
  /** Drivable extents, used as a last-resort clamp. */
  bounds: { minX: number; maxX: number; minZ: number; maxZ: number };
  playerSpawn: SpawnPoint;
  /** At least 3 entries. Each electric car starts at one of these. */
  targetSpawns: SpawnPoint[];
  /** Optional patrol loops. Each target follows the loop with the same index, when present. */
  targetPatrols: Array<Array<{ x: number; z: number }>>;
  colliders: ObstacleBox[];
}

/** Read-only view of the state that the HUD needs. Built by `src/game.ts`. */
export interface HudSnapshot {
  speedKmh: number;
  /** 0..1 */
  nitro: number;
  nitroActive: boolean;
  /** 0..1 */
  charge: number;
  canFire: boolean;
  drifting: boolean;
  driftDuration: number;
  chain: number;
  money: number;
  destroyed: number;
  targetsRemaining: number;
  targetsTotal: number;
  targetAcquired: boolean;
  lastReward: number;
  time: number;
  /** True while the car moves backwards. */
  reversing: boolean;
  /** 0..1 fraction of the lightning cooldown remaining (0 = can fire again). */
  cooldown01: number;
  /** Seconds remaining in which a new drift extends the chain (0 when no chain is pending). */
  chainWindow: number;
  /** True while nitro is actually refilling this frame. */
  nitroRecharging: boolean;
}
