/**
 * Write `src/microScenes/SCENE_CATALOG.md` from the typed registry.
 *
 *   node scripts/scene-catalog.mjs            rewrite the catalogue
 *   node scripts/scene-catalog.mjs --check    fail if it is out of date (for CI and for review)
 *
 * NOTHING IN THE CATALOGUE IS MAINTAINED BY HAND. Every number in it — how many scenes there are,
 * where each can stand, how many actors and props and dialogue variants it has, which shared
 * behaviours it uses, what it costs — is read out of `src/microScenes/registry.ts`, so it can
 * never drift from the code the way a hand-written table does. Adding a scene and re-running this
 * is the whole of the documentation work.
 *
 * The scene definitions import nothing at runtime, so Node loads them straight.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
import { MICRO_SCENES, behaviorUsage, sceneBehaviors, sceneCost, sceneLines } from '../src/microScenes/registry.ts';
import { SHARED_BEHAVIORS } from '../src/microScenes/behaviors.ts';
import { VOICE_PROFILES, resolvedVoice, voiceConfigured } from '../src/microScenes/voices.ts';
import { validateCatalog } from '../src/microScenes/validate.ts';

const root = fileURLToPath(new URL('..', import.meta.url));
const target = join(root, 'src', 'microScenes', 'SCENE_CATALOG.md');
const check = process.argv.includes('--check');

const list = (xs) => (xs.length > 0 ? xs.join(', ') : '—');
const code = (xs) => (xs.length > 0 ? xs.map((x) => `\`${x}\``).join(' ') : '—');

/** Which voice profiles a scene needs, and which of them nobody records yet. */
function voicesOf(scene) {
  const needed = new Set();
  for (const line of sceneLines(scene)) {
    const profile = line.voice ?? scene.actors.find((a) => a.id === line.speaker)?.voice;
    if (profile) needed.add(profile);
  }
  return {
    needed: [...needed],
    missing: [...needed].filter((p) => !voiceConfigured(p)),
  };
}

function sceneSection(scene) {
  const behaviors = sceneBehaviors(scene);
  const voices = voicesOf(scene);
  const reactions = scene.reactions ?? [];
  const conditions = (scene.conditions ?? []).map((c) => c.kind);
  const variants = scene.dialogueVariants.map(
    (v) => `\`${v.id}\`${v.conditions ? ` (${v.conditions.map((c) => c.kind).join(', ')})` : ''}`,
  );
  const status = voices.missing.length > 0 ? `${scene.status} — missing voice: ${list(voices.missing)}` : scene.status;
  return [
    `### ${scene.title} — \`${scene.id}\``,
    '',
    scene.description,
    '',
    `| | |`,
    `| --- | --- |`,
    `| Category | \`${scene.category}\` |`,
    `| Tags | ${code(scene.tags)} |`,
    `| Anchors | ${code(scene.compatibleAnchorTypes)} |`,
    `| Requires tags | ${code(scene.requiredAnchorTags ?? [])} |`,
    `| Forbids tags | ${code(scene.forbiddenAnchorTags ?? [])} |`,
    `| Actors / props | ${scene.actors.length} / ${scene.props.length} |`,
    `| Dialogue variants | ${scene.dialogueVariants.length} (${sceneLines(scene).length} lines) |`,
    `| Variants | ${variants.join('<br>')} |`,
    `| Shared behaviours | ${code(behaviors)} |`,
    `| Reactions | ${code(reactions.map((r) => `${r.id}:${r.trigger}`))} |`,
    `| Conditions | ${code(conditions)} |`,
    `| Weight / cooldown | ${scene.weight} / ${scene.cooldownSeconds}s |`,
    `| Radii (spawn/act/talk/despawn) | ${scene.spawnDistance} / ${scene.activationDistance} / ${scene.dialogueDistance} / ${scene.despawnDistance} m |`,
    `| Budget | ${scene.performanceBudget.maxActors} actors, ${scene.performanceBudget.maxAnimatedActors} animated, ${scene.performanceBudget.maxParticles} particles, no lights, no physics |`,
    `| Cost | ${Math.round(sceneCost(scene))} |`,
    `| Voices | ${code(voices.needed)} |`,
    `| Status | **${status}** |`,
    '',
  ].join('\n');
}

function build() {
  const usage = behaviorUsage();
  const issues = validateCatalog();
  const errors = issues.filter((i) => i.severity === 'error');
  const warnings = issues.filter((i) => i.severity === 'warning');
  const police = MICRO_SCENES.filter(
    (s) =>
      s.category === 'police' ||
      s.tags.includes('police-reactive') ||
      (s.reactions ?? []).some((r) => r.trigger === 'policeNear' || r.trigger === 'playerWanted'),
  );
  const needsAudio = MICRO_SCENES.filter((s) => s.status !== 'complete');
  const expensive = [...MICRO_SCENES].sort((a, b) => sceneCost(b) - sceneCost(a));

  const out = [];
  out.push('# Urban micro-scenes — catalogue');
  out.push('');
  out.push('<!-- GENERATED by `node scripts/scene-catalog.mjs` from `src/microScenes/registry.ts`. Do not edit. -->');
  out.push('');
  out.push(
    'Short situations the city is already having when the player drives past. They are never missions, never',
    'rewards, never prompts: two or three people, one conversation per appearance, at most one reaction to the car.',
  );
  out.push('');
  out.push(`**${MICRO_SCENES.length} scenes**, ${MICRO_SCENES.reduce((n, s) => n + sceneLines(s).length, 0)} recorded lines, ` +
    `${Object.keys(SHARED_BEHAVIORS).length} shared behaviour blocks.`);
  out.push('');

  /* ---------------------------------------------------------------- the quick answers */

  out.push('## At a glance');
  out.push('');
  out.push('| Scene | Category | Anchors | Actors | Props | Variants | Cooldown | Cost | Status |');
  out.push('| --- | --- | --- | --- | --- | --- | --- | --- | --- |');
  for (const s of MICRO_SCENES) {
    out.push(
      `| [${s.title}](#${s.id}) \`${s.id}\` | ${s.category} | ${s.compatibleAnchorTypes.join(' ')} | ` +
        `${s.actors.length} | ${s.props.length} | ${s.dialogueVariants.length} | ${s.cooldownSeconds}s | ` +
        `${Math.round(sceneCost(s))} | ${s.status} |`,
    );
  }
  out.push('');
  out.push(`**Which scenes involve the police?** ${list(police.map((s) => `\`${s.id}\``))}`);
  out.push('');
  out.push(`**Which still need audio or assets?** ${list(needsAudio.map((s) => `\`${s.id}\` (${s.status})`))}`);
  out.push('');
  out.push(`**Which are most expensive?** ${list(expensive.slice(0, 3).map((s) => `\`${s.id}\` (${Math.round(sceneCost(s))})`))}`);
  out.push('');

  /* ---------------------------------------------------------------- behaviours */

  out.push('## Shared behaviour blocks');
  out.push('');
  out.push('A scene composes these by name; each is implemented exactly once in `src/microScenes/behaviors.ts`.');
  out.push('');
  out.push('| Block | Used by | What it does |');
  out.push('| --- | --- | --- |');
  for (const [id, spec] of Object.entries(SHARED_BEHAVIORS)) {
    const scenes = usage.get(id) ?? [];
    out.push(`| \`${id}\` | ${scenes.length} scene${scenes.length === 1 ? '' : 's'} | ${spec.summary} |`);
  }
  out.push('');

  /* ---------------------------------------------------------------- voices */

  out.push('## Voices');
  out.push('');
  out.push(
    'A profile with no recording and no stand-in keeps its lines and its speaker assignments; the variants that',
    'need it simply are not selected, and the rest of the system is unaffected.',
  );
  out.push('');
  out.push('| Profile | Presenting | Own recording | Heard as | Lines |');
  out.push('| --- | --- | --- | --- | --- |');
  for (const p of Object.values(VOICE_PROFILES)) {
    const heard = resolvedVoice(p.id);
    const lines = MICRO_SCENES.reduce(
      (n, s) => n + sceneLines(s).filter((l) => (l.voice ?? s.actors.find((a) => a.id === l.speaker)?.voice) === p.id).length,
      0,
    );
    out.push(
      `| \`${p.id}\` | ${p.presenting} | ${p.characterId ? `\`${p.characterId}\`` : '—'} | ` +
        `${heard ? (heard.id === p.id ? 'itself' : `\`${heard.id}\` (placeholder)`) : '**nobody — silent**'} | ${lines} |`,
    );
  }
  out.push('');

  /* ---------------------------------------------------------------- the scenes */

  out.push('## The scenes');
  out.push('');
  for (const s of MICRO_SCENES) out.push(sceneSection(s));

  /* ---------------------------------------------------------------- validation */

  out.push('## Validation');
  out.push('');
  if (errors.length === 0) out.push('No errors.');
  else for (const i of errors) out.push(`- **error** — ${i.scene}: ${i.message}`);
  out.push('');
  if (warnings.length === 0) out.push('No warnings.');
  else for (const i of warnings) out.push(`- warning — ${i.scene}: ${i.message}`);
  out.push('');
  out.push('### Known gaps');
  out.push('');
  out.push(
    '- One female clone (`npc-femenino-1`). `npc-femenina-2` is voiced by it at a lower rate, as `npc-masculino-2` and',
    '  `npc-policia-1` are by `npc-masculino-1`: honest placeholders, so two sides of a conversation are still two people.',
    '- The `horn` reaction trigger has no input in this build — the game has no horn, and a micro-scene is not allowed',
    '  to add one. `double-parking-argument`\'s reply is written, generated and reachable from the debug tools.',
    '- The anchor types `dark-corner`, `industrial-alley` and `dark-service-road` are supported but Bandido Metro\'s back',
    '  lanes carry no measured pavement, so it lays none of them down today.',
  );
  out.push('');
  return out.join('\n');
}

const text = build();
if (check) {
  const current = await readFile(target, 'utf8').catch(() => '');
  if (current.trim() !== text.trim()) {
    console.error('SCENE_CATALOG.md is out of date. Run: node scripts/scene-catalog.mjs');
    process.exit(1);
  }
  console.log('SCENE_CATALOG.md is up to date.');
} else {
  await writeFile(target, text, 'utf8');
  console.log(`wrote ${target} (${MICRO_SCENES.length} scenes)`);
}
