import { createHash, randomUUID } from 'node:crypto';
import { mkdir, readFile, rename, rm, stat, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { readJson, send } from '../api.mjs';
import { characterVoices } from './voices.mjs';

/**
 * Spoken dialogue, generated by ElevenLabs on first request and served from a cache after.
 *
 *   POST /api/dialogue/speech  {characterId, text}  → {audioUrl, cached}
 *   GET  /generated-dialogue/<sha256>.mp3            the cached clip
 *
 * A proof of concept: the key and voice ids never leave this process, the client only names a
 * character from `voices.mjs`, and every failure is an HTTP status the game treats as "no voice".
 */

export const MAX_TEXT_CHARS = 500;
const ELEVENLABS_TTS = 'https://api.elevenlabs.io/v1/text-to-speech';
const GENERATE_TIMEOUT_MS = 20_000;
const RATE_WINDOW_MS = 60_000;
// The intro warms ~22 lines at once and then asks for each again as it is said.
const RATE_MAX_PER_WINDOW = 60;
const CLIP_PATH = /^\/generated-dialogue\/([0-9a-f]{64})\.mp3$/;

export class SpeechError extends Error {
  constructor(status, message) {
    super(message);
    this.status = status;
  }
}

/** Trim and collapse runs of whitespace. Nothing else: case and punctuation are the line. */
export function normalizeText(text) {
  return typeof text === 'string' ? text.trim().replace(/\s+/g, ' ') : '';
}

/** JSON with object keys sorted at every depth, so equal inputs always hash equal. */
function stableStringify(value) {
  if (Array.isArray(value)) return `[${value.map(stableStringify).join(',')}]`;
  if (value && typeof value === 'object') {
    return `{${Object.keys(value)
      .sort()
      .map((k) => `${JSON.stringify(k)}:${stableStringify(value[k])}`)
      .join(',')}}`;
  }
  return JSON.stringify(value);
}

/** SHA-256 over everything that can change the audio. */
export function speechCacheKey({ normalizedText, characterId, voice }) {
  const material = {
    normalizedText,
    characterId,
    voiceId: voice.voiceId,
    voiceVersion: voice.version,
    modelId: voice.modelId,
    outputFormat: voice.outputFormat,
    voiceSettings: voice.voiceSettings,
  };
  return createHash('sha256').update(stableStringify(material)).digest('hex');
}

/**
 * The cache is three calls — `has`, `get`, `put` — so it can become S3 or R2 later without
 * touching anything else here.
 *
 * This one is the local filesystem, which only persists on one stable Node server: every deploy
 * (Elastic Beanstalk replaces the app directory) and every extra or serverless instance starts
 * with an empty cache, and the lines are generated again.
 */
export function createFsSpeechCache(dir) {
  const file = (key) => join(dir, `${key}.mp3`);
  return {
    async has(key) {
      try {
        return (await stat(file(key))).isFile();
      } catch {
        return false;
      }
    },
    async get(key) {
      try {
        return await readFile(file(key));
      } catch {
        return null;
      }
    },
    async put(key, bytes) {
      await mkdir(dir, { recursive: true });
      // Written aside and renamed in, so a reader never sees half a clip.
      const tmp = `${file(key)}.${randomUUID()}.tmp`;
      try {
        await writeFile(tmp, bytes);
        await rename(tmp, file(key));
      } catch (err) {
        await rm(tmp, { force: true });
        throw err;
      }
    },
  };
}

function toElevenLabsSettings(s) {
  return {
    stability: s.stability,
    similarity_boost: s.similarityBoost,
    style: s.style,
    use_speaker_boost: s.useSpeakerBoost,
    speed: s.speed,
  };
}

export function createDialogueSpeech({
  env = process.env,
  cache,
  fetchImpl = globalThis.fetch,
  log = () => {},
  dev = env.NODE_ENV !== 'production',
  now = Date.now,
} = {}) {
  const voices = characterVoices(env);
  /** cache key → the generation already under way for it. */
  const inFlight = new Map();
  /** client address → { start, count } for the current window. */
  const hits = new Map();
  const devLog = (msg) => {
    if (dev) log(msg);
  };

  async function generate(characterId, voice, text, key) {
    const apiKey = env.ELEVENLABS_API_KEY;
    if (!apiKey || !voice.voiceId) throw new SpeechError(503, 'speech is not configured');
    const started = now();
    let res;
    try {
      res = await fetchImpl(
        `${ELEVENLABS_TTS}/${encodeURIComponent(voice.voiceId)}?output_format=${encodeURIComponent(voice.outputFormat)}`,
        {
          method: 'POST',
          headers: { 'xi-api-key': apiKey, 'content-type': 'application/json', accept: 'audio/mpeg' },
          body: JSON.stringify({ text, model_id: voice.modelId, voice_settings: toElevenLabsSettings(voice.voiceSettings) }),
          signal: AbortSignal.timeout(GENERATE_TIMEOUT_MS),
        },
      );
    } catch (err) {
      log(`[TTS] request failed (${err?.name || 'error'}): ${characterId}`);
      throw new SpeechError(502, 'speech generation failed');
    }
    if (!res.ok) {
      // The provider's own message (quota, unknown voice…) is for this log, never the client.
      const detail = dev ? ` ${(await res.text().catch(() => '')).slice(0, 200)}` : '';
      log(`[TTS] ElevenLabs answered ${res.status}: ${characterId}${detail}`);
      throw new SpeechError(502, 'speech generation failed');
    }
    const bytes = Buffer.from(await res.arrayBuffer());
    if (bytes.length === 0) throw new SpeechError(502, 'speech generation failed');
    await cache.put(key, bytes);
    devLog(`[TTS] generated in ${now() - started}ms: ${characterId}`);
  }

  /** Validate, then answer from the cache or generate once. Throws `SpeechError`. */
  async function synthesize(characterId, rawText) {
    if (typeof characterId !== 'string' || !Object.hasOwn(voices, characterId)) {
      throw new SpeechError(400, 'unknown characterId');
    }
    const text = normalizeText(rawText);
    if (!text) throw new SpeechError(400, 'text is required');
    if (text.length > MAX_TEXT_CHARS) throw new SpeechError(400, `text is longer than ${MAX_TEXT_CHARS} characters`);

    const voice = voices[characterId];
    const key = speechCacheKey({ normalizedText: text, characterId, voice });
    const result = { key, audioUrl: `/generated-dialogue/${key}.mp3` };

    if (await cache.has(key)) {
      devLog(`[TTS] cache hit: ${characterId}`);
      return { ...result, cached: true };
    }
    devLog(`[TTS] cache miss: ${characterId}`);
    let pending = inFlight.get(key);
    if (!pending) {
      pending = generate(characterId, voice, text, key).finally(() => inFlight.delete(key));
      inFlight.set(key, pending);
    }
    await pending;
    return { ...result, cached: false };
  }

  function allow(req) {
    const forwarded = String(req.headers['x-forwarded-for'] || '').split(',')[0].trim();
    const who = forwarded || req.socket?.remoteAddress || 'unknown';
    const t = now();
    if (hits.size > 5000) hits.clear();
    const entry = hits.get(who);
    if (!entry || t - entry.start >= RATE_WINDOW_MS) {
      hits.set(who, { start: t, count: 1 });
      return true;
    }
    entry.count++;
    return entry.count <= RATE_MAX_PER_WINDOW;
  }

  async function speech(req, res) {
    if (!String(req.headers['content-type'] || '').startsWith('application/json')) {
      return send(res, 415, { error: 'expected application/json' });
    }
    if (!allow(req)) return send(res, 429, { error: 'too many requests' });
    const { body, error } = await readJson(req);
    if (error) return send(res, 400, { error });
    try {
      const { audioUrl, cached } = await synthesize(body?.characterId, body?.text);
      send(res, 200, { audioUrl, cached });
    } catch (err) {
      if (err instanceof SpeechError) return send(res, err.status, { error: err.message });
      log(`[TTS] failed: ${err?.message || err}`);
      send(res, 500, { error: 'speech failed' });
    }
  }

  async function clip(res, key) {
    const bytes = await cache.get(key);
    if (!bytes) return send(res, 404, { error: 'not found' });
    res.writeHead(200, {
      'content-type': 'audio/mpeg',
      'content-length': bytes.length,
      // Named by the hash of everything that shaped it, so the URL never means other bytes.
      'cache-control': 'public, max-age=31536000, immutable',
      'x-content-type-options': 'nosniff',
    });
    res.end(bytes);
  }

  return {
    synthesize,
    /** Claims the two dialogue paths; false for anything else. */
    handle(req, res, url) {
      if (url.pathname === '/api/dialogue/speech') {
        if (req.method !== 'POST') send(res, 405, { error: 'method not allowed' });
        else speech(req, res);
        return true;
      }
      const m = CLIP_PATH.exec(url.pathname);
      if (m) {
        if (req.method !== 'GET' && req.method !== 'HEAD') send(res, 405, { error: 'method not allowed' });
        else clip(res, m[1]).catch(() => send(res, 500, { error: 'read failed' }));
        return true;
      }
      return false;
    },
  };
}
